--- 
artifacts: 
  discard-paths: true
  files: 
    - target/awscodebuildeployproject*/*
cache: 
  paths: 
    - /root/.m2/**/*
phases: 
  build: 
    commands: 
      - "echo entered the build phase...."
      - "echo Build started on 'date'"
      - "mvn clean package"
  post_build: 
    command: 
      - "echo Build completed sucessfully"
version: 0.2
